CC = clang
CFLAGS = -Wall -Wextra -std=c99 $(shell sdl2-config --cflags)
LDFLAGS = $(shell sdl2-config --libs)

SRCS = main.c
# Later add: game.c input.c render.c
OBJS = $(SRCS:.c=.o)
TARGET = c_snake

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

run: $(TARGET)
	./$(TARGET)

.PHONY: all clean run
